PRAGMA foreign_keys = OFF;

CREATE TABLE "CenterOfGravityData" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"Timestamp"  TEXT NOT NULL,
"X"  REAL NOT NULL,
"Y"  REAL NOT NULL,
"PersonRef"  INTEGER NOT NULL,
CONSTRAINT "Ref_Person" FOREIGN KEY ("PersonRef") REFERENCES "Person" ("ID")
);

CREATE TABLE "Log" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"Ref_Person"  INTEGER NOT NULL,
"Message"  TEXT,
CONSTRAINT "Ref_Person" FOREIGN KEY ("Ref_Person") REFERENCES "Person" ("ID")
);

CREATE TABLE "Person" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"Fname"  TEXT,
"Lname"  TEXT
);

CREATE TABLE "SensorData" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"Timestamp"  TEXT NOT NULL,
"BottomLeft"  REAL,
"BottomRight"  REAL,
"TopLeft"  REAL,
"TopRight"  REAL,
"PersonRef"  INTEGER NOT NULL,
CONSTRAINT "Ref_Person" FOREIGN KEY ("ID") REFERENCES "Person" ("ID")
);

CREATE TABLE "Weight" (
"ID"  INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
"Timestamp"  TEXT NOT NULL,
"WeightKg"  INTEGER NOT NULL,
"PersonRef"  INTEGER NOT NULL,
CONSTRAINT "Ref_Person" FOREIGN KEY ("PersonRef") REFERENCES "Person" ("ID")
);